baseURL = "https://blogdraft.maxence.site/"
languageCode = "en-us"
title = "Max1Truc's blog"
theme = "color-your-world"

[params.style]

  # Dark mode as default
  # User preferences (site/system settings) will still have priority over it
  # The default is false
  isDark = true

  # Accent colors for light and dark mode respectively
  lightAccent  = "#225670" # Default is "#225670"
  darkAccent   = "#27a41c" # Default is "#dd587c"

  # More colors, pick as many as you want (not really sure if there's a limit)
  # Apparently these may not show up on every modern browser (ie.: Firefox)
  # There's no default value. Used here just as example
  presets = [ "#1f676b", "#f3a530", "#902b37", "#1dbc91", "#754e85", "#7fc121", "#a8314a", "#ff7433", "#3e6728", "#c063bd" ]

